
_name_: ribo_only
## commented out the shifted dataset for now
dataset_path:
  green_2020: "Datasets/data/weighted_datasets_ribo_replicas/green_2020.parquet"
  #eichhorn_2014: "Datasets/data/weighted_datasets_ribo_replicas/eichhorn_2014.parquet"
  #ingolia_2014: "Datasets/data/weighted_datasets_ribo_replicas/ingolia_2014.parquet"
  kulakovskiy_2024: "Datasets/data/weighted_datasets_ribo_replicas/kulakovskiy_2024.parquet"
  kutay_2021: "Datasets/data/weighted_datasets_ribo_replicas/kutay_2021.parquet"
  sauer_2019: "Datasets/data/weighted_datasets_ribo_replicas/sauer_2019.parquet"
  #tsvetanova_2025: "Datasets/data/weighted_datasets_ribo_replicas/tsvetanova_2025.parquet"
  wakigawa_2025: "Datasets/data/weighted_datasets_ribo_replicas/wakigawa_2025.parquet"
  wan_2019: "Datasets/data/weighted_datasets_ribo_replicas/wan_2019.parquet"
  wang_2016: "Datasets/data/weighted_datasets_ribo_replicas/wang_2016.parquet"
  wangHEK_2022: "Datasets/data/weighted_datasets_ribo_replicas/wangHEK_2022.parquet"
  weber_2022: "Datasets/data/weighted_datasets_ribo_replicas/weber_2022.parquet"
  weber_2024: "Datasets/data/weighted_datasets_ribo_replicas/weber_2024.parquet"
  wu_2019: "Datasets/data/weighted_datasets_ribo_replicas/wu_2019.parquet"
  wu_2020: "Datasets/data/weighted_datasets_ribo_replicas/wu_2020.parquet"
  gillen_2019: "Datasets/data/weighted_datasets_ribo_replicas/gillen_2019.parquet"
  grimson_2019: "Datasets/data/weighted_datasets_ribo_replicas/grimson_2019.parquet"
  iwasaki_2014: "Datasets/data/weighted_datasets_ribo_replicas/iwasaki_2014.parquet"
  iwasaki_2018: "Datasets/data/weighted_datasets_ribo_replicas/iwasaki_2018.parquet"
  iwasaki_2021: "Datasets/data/weighted_datasets_ribo_replicas/iwasaki_2021.parquet"
  kito_2023: "Datasets/data/weighted_datasets_ribo_replicas/kito_2023.parquet"
  kulakovskiy_2019:  "Datasets/data/weighted_datasets_ribo_replicas/kulakovskiy_2019.parquet"
  weber_2020:  "Datasets/data/weighted_datasets_ribo_replicas/weber_2020.parquet"
  riepe_2018:  "Datasets/data/weighted_datasets_ribo_replicas/riepe_2018.parquet"
  sako_2020:  "Datasets/data/weighted_datasets_ribo_replicas/sako_2020.parquet"
  cui_2024:  "Datasets/data/weighted_datasets_ribo_replicas/cui_2024.parquet"
  ichihara_2021:  "Datasets/data/weighted_datasets_ribo_replicas/ichihara_2021.parquet"
  iwasaki_2019:  "Datasets/data/weighted_datasets_ribo_replicas/iwasaki_2019.parquet"
  martinez_2019:  "Datasets/data/weighted_datasets_ribo_replicas/martinez_2019.parquet"
  sidrauski_2015:  "Datasets/data/weighted_datasets_ribo_replicas/sidrauski_2015.parquet"
  song_2019:  "Datasets/data/weighted_datasets_ribo_replicas/song_2019.parquet"
  volegova_2018:  "Datasets/data/weighted_datasets_ribo_replicas/volegova_2018.parquet"
  iwasaki_2020: "./Datasets/data/weighted_datasets_ribo_replicas/iwasaki_2020.parquet"

